### ISSUE TITLE
How to point to a live Salesforce Org ?

### ISSUE THREAD

**Issue by dkalichak** [certinia/object-model-tool#1]
HI, this looks like a very useful utility. I have downloaded it, and have it working against the local sample data. I couldn't find any instructions on how to point it to a live org so as to generate a ERD from that. Is the procedure documented somewhere ?

**Comment by bslaterffdc-zz** [comment]
You need to change config.properties to use a 'RetreiveServiceRemote' instead of local. Then the output you get when you run it will tell you what params it needs to connect. We aren't sure what it will be able to pull from a live org in terms of packaged objects. Anything unpackaged will certainly be returned as this was one of our main use cases.

**Comment by bslaterffdc-zz** [comment]
I am happy to re-open this if there are any more questions/problems but I am working on extending the readme to cover configuration options.

**Comment by dkalichak** [comment]
Ok, sounds good.

**Comment by dkalichak** [comment]
When I change my config.properties, then do another 'Ant Run', the config.properties gets overwrittenn back to having:

retrieve=com.financialforce.objectmodelutil.model.processor.retrieve.RetrieveProcessorLocal 

in it.

**Comment by bslaterffdc-zz** [comment]
Edit the property inside the ant build.xml file instead of in config.properties. The ant script overwrites the config file with its own internal variables every time it runs.

**Comment by dkalichak** [comment]
Ok, getting odd errors after making that change. I'll put this aside for a bit, and check back once you've had a chance to update the doc, and when it's been determined if it will work with FF managed packages.

**Comment by bslaterffdc-zz** [comment]
Ok thanks for the feedback, could you open the manage package problem as a separate issue from the documentation problems we've discussed?
